# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

###
The MIT License (MIT)

Copyright (c) 2015 William Hilton

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
###


### If you're using Stripe for payments ###

payWithStripe = (e) ->
  e.preventDefault()

  ### Visual feedback ###

  $form.find('[type=submit]').html 'Validating <i class="fa fa-spinner fa-pulse"></i>'
  PublishableKey = 'pk_test_6pRNASCoBOKtIshFeQd4XMUh'
  # Replace with your API publishable key
  Stripe.setPublishableKey PublishableKey
  Stripe.card.createToken $form, (status, response) ->
    console.log
    if response.error

      ### Visual feedback ###

      $form.find('[type=submit]').html 'Try again'

      ### Show Stripe errors on the form ###

      $form.find('.payment-errors').text response.error.message
      $form.find('.payment-errors').closest('.row').show()
    else

      ### Visual feedback ###

      $form.find('[type=submit]').html 'Processing <i class="fa fa-spinner fa-pulse"></i>'

      ### Hide Stripe errors on the form ###

      $form.find('.payment-errors').closest('.row').hide()
      $form.find('.payment-errors').text ''
      # response contains id and card, which contains additional card details
      token = response.id
      console.log token
      # AJAX
      $.post('/account/stripe_card_token', token: token).done((data, textStatus, jqXHR) ->
        $form.find('[type=submit]').html('Payment successful <i class="fa fa-check"></i>').prop 'disabled', true
        return
      ).fail (jqXHR, textStatus, errorThrown) ->
        $form.find('[type=submit]').html('There was a problem').removeClass('success').addClass 'error'

        ### Show Stripe errors on the form ###

        $form.find('.payment-errors').text 'Try refreshing the page and trying again.'
        $form.find('.payment-errors').closest('.row').show()
        return
    return
  return

#$form.on 'submit', payWithStripe

### Form validation ###
$(document).ready (ev) ->
  $form = $('#payment-form')

  jQuery.validator.addMethod 'month', ((value, element) ->
    @optional(element) or /^(01|02|03|04|05|06|07|08|09|10|11|12)$/.test(value)
  ), 'Please specify a valid 2-digit month.'
  jQuery.validator.addMethod 'year', ((value, element) ->
    @optional(element) or /^[0-9]{2}$/.test(value)
  ), 'Please specify a valid 2-digit year.'
  validator = $form.validate(
    rules:
      cardNumber:
        required: true
        creditcard: true
        digits: true
      expMonth:
        required: true
        month: true
      expYear:
        required: true
        year: true
      cvCode:
        required: true
        digits: true
    highlight: (element) ->
      $(element).closest('.form-control').removeClass('success').addClass 'error'
      return
    unhighlight: (element) ->
      $(element).closest('.form-control').removeClass('error').addClass 'success'
      return
    errorPlacement: (error, element) ->
      $(element).closest('.form-group').append error
      return
  )

  paymentFormReady = ->
    if $form.find('[name=cardNumber]').hasClass('success') and $form.find('[name=expMonth]').hasClass('success') and $form.find('[name=expYear]').hasClass('success') and $form.find('[name=cvCode]').val().length > 1
      true
    else
      false



  $form.find('[type=submit]').prop 'disabled', true
  readyInterval = setInterval((->
    if paymentFormReady()
      $form.find('[type=submit]').prop 'disabled', false
      clearInterval readyInterval
    return
  ), 250)

# ---
# generated by js2coffee 2.0.3